// Chargement dans un variable de la balise <div id="jsloaded"....
var jsloaded=document.querySelector("#jsLoaded");

// Chargement dans un variable de la balise <div id="jsloaded"....
jsloaded.style.backgroundColor="green";

// Chargement dans un variable de la balise <div id="jsloaded"....
jsloaded.innerText="le js est chargé";